import js from '@eslint/js'
import globals from 'globals'
import tseslint from 'typescript-eslint'
import pluginReact from 'eslint-plugin-react'
import json from '@eslint/json'
import markdown from '@eslint/markdown'
import css from '@eslint/css'
import { defineConfig } from 'eslint/config'
import prettier from 'eslint-config-prettier'
import lint from 'lenix/lint' with { type: 'json' }
import stylistic from '@stylistic/eslint-plugin'

export default defineConfig([
	{
		files: ['**/*.{js,mjs,cjs,ts,mts,cts,jsx,tsx}'],
		plugins: {
			js,
			'@stylistic': stylistic,
		},
		extends: ['js/recommended', prettier],
		languageOptions: {
			globals: {
				...globals.browser,
				...globals.node,
			},
			parserOptions: {
				projectService: true,
				tsconfigRootDir: import.meta.dirname,
			},
		},
		rules: {
			...(lint.strict as any),
			'@stylistic/array-bracket-newline': 'warn',
			'@stylistic/array-bracket-spacing': 'warn',
			'@stylistic/array-element-newline': ['warn', 'consistent'],
			'@stylistic/arrow-parens': 'warn',
			'@stylistic/arrow-spacing': 'warn',
			'@stylistic/block-spacing': 'warn',
			'@stylistic/brace-style': 'warn',
			'@stylistic/comma-dangle': 'warn',
			'@stylistic/comma-spacing': 'warn',
			'@stylistic/comma-style': 'warn',
			'@stylistic/computed-property-spacing': 'warn',
			'@stylistic/curly-newline': 'warn',
			'@stylistic/dot-location': 'warn',
			'@stylistic/eol-last': 'warn',
			'@stylistic/function-call-argument-newline': 'warn',
			'@stylistic/function-call-spacing': 'warn',
			'@stylistic/function-paren-newline': 'warn',
			'@stylistic/generator-star-spacing': 'warn',
			'@stylistic/implicit-arrow-linebreak': 'warn',
			'@stylistic/indent': ['warn', 'tab'],
			'@stylistic/indent-binary-ops': 'warn',
			'@stylistic/jsx-child-element-spacing': 'warn',
			'@stylistic/jsx-closing-bracket-location': 'warn',
			'@stylistic/jsx-closing-tag-location': 'warn',
			'@stylistic/jsx-curly-brace-presence': 'warn',
			'@stylistic/jsx-curly-newline': 'warn',
			'@stylistic/jsx-curly-spacing': 'warn',
			'@stylistic/jsx-equals-spacing': 'warn',
			'@stylistic/jsx-first-prop-new-line': 'warn',
			'@stylistic/jsx-function-call-newline': 'warn',
			'@stylistic/jsx-indent-props': ['warn', 0],
			'@stylistic/jsx-max-props-per-line': ['warn', { maximum: 3 }],
			'@stylistic/jsx-newline': ['warn', { prevent: true }],
			'@stylistic/jsx-one-expression-per-line': ['warn', { allow: 'non-jsx' }],
			'@stylistic/jsx-pascal-case': 'warn',
			'@stylistic/exp-jsx-props-style': 'warn',
			'@stylistic/jsx-quotes': ['warn', 'prefer-single'],
			'@stylistic/jsx-self-closing-comp': 'warn',
			'@stylistic/jsx-tag-spacing': 'warn',
			'@stylistic/jsx-wrap-multilines': 'warn',
			'@stylistic/key-spacing': 'warn',
			'@stylistic/keyword-spacing': 'warn',
			'@stylistic/line-comment-position': 'warn',
			'@stylistic/linebreak-style': 'warn',
			'@stylistic/lines-around-comment': 'warn',
			'@stylistic/lines-between-class-members': 'warn',
			'@stylistic/exp-list-style': 'warn',
			'@stylistic/max-len': 'warn',
			'@stylistic/max-statements-per-line': 'warn',
			'@stylistic/member-delimiter-style': [
				'error',
				{
					multiline: {
						delimiter: 'none',
					},
					singleline: {
						delimiter: 'semi',
						requireLast: false,
					},
				},
			],
			'@stylistic/multiline-comment-style': 'warn',
			'@stylistic/multiline-ternary': 'warn',
			'@stylistic/new-parens': 'warn',
			'@stylistic/newline-per-chained-call': 'warn',
			'@stylistic/no-confusing-arrow': 'warn',
			'@stylistic/no-extra-parens': ['warn', 'all', { ignoreJSX: 'all' }],
			'@stylistic/no-extra-semi': 'warn',
			'@stylistic/no-floating-decimal': 'warn',
			'@stylistic/no-mixed-operators': 'warn',
			'@stylistic/no-mixed-spaces-and-tabs': 'warn',
			'@stylistic/no-multi-spaces': 'warn',
			'@stylistic/no-multiple-empty-lines': 'warn',
			'@stylistic/no-tabs': ['warn', { allowIndentationTabs: true }],
			'@stylistic/no-trailing-spaces': 'warn',
			'@stylistic/no-whitespace-before-property': 'warn',
			'@stylistic/nonblock-statement-body-position': 'warn',
			'@stylistic/object-curly-newline': 'warn',
			'@stylistic/object-curly-spacing': ['warn', 'always'],
			'@stylistic/object-property-newline': 'warn',
			'@stylistic/one-var-declaration-per-line': 'warn',
			'@stylistic/operator-linebreak': 'warn',
			'@stylistic/padded-blocks': ['warn', 'never'],
			'@stylistic/padding-line-between-statements': 'warn',
			'@stylistic/quote-props': ['warn', 'as-needed'],
			'@stylistic/quotes': ['warn', 'single', { avoidEscape: true }],
			'@stylistic/rest-spread-spacing': 'warn',
			'@stylistic/semi': ['warn', 'never'],
			'@stylistic/semi-spacing': 'warn',
			'@stylistic/semi-style': 'warn',
			'@stylistic/space-before-blocks': 'warn',
			'@stylistic/space-before-function-paren': ['warn', 'never'],
			'@stylistic/space-in-parens': 'warn',
			'@stylistic/space-infix-ops': 'warn',
			'@stylistic/space-unary-ops': 'warn',
			'@stylistic/spaced-comment': 'warn',
			'@stylistic/switch-colon-spacing': 'warn',
			'@stylistic/template-curly-spacing': 'warn',
			'@stylistic/template-tag-spacing': 'warn',
			'@stylistic/type-annotation-spacing': 'warn',
			'@stylistic/type-generic-spacing': 'warn',
			'@stylistic/type-named-tuple-spacing': 'warn',
			'@stylistic/wrap-iife': 'warn',
			'@stylistic/wrap-regex': 'warn',
			'@stylistic/yield-star-spacing': 'warn',
		},
	},
	tseslint.configs.recommended,
	pluginReact.configs.flat['jsx-runtime'],
	{
		files: ['**/*.json'],
		plugins: { json },
		language: 'json/json',
		extends: ['json/recommended'],
	},
	{
		files: ['**/*.jsonc'],
		plugins: { json },
		language: 'json/jsonc',
		extends: ['json/recommended'],
	},
	{
		files: ['**/*.json5'],
		plugins: { json },
		language: 'json/json5',
		extends: ['json/recommended'],
	},
	{
		files: ['**/*.md'],
		plugins: { markdown },
		language: 'markdown/gfm',
		extends: ['markdown/recommended'],
	},
	{
		files: ['**/*.css'],
		plugins: { css },
		language: 'css/css',
		extends: ['css/recommended'],
	},
])
